# -*- coding: utf-8 -*-
"""Ani_s_project.ipynb

Automatically generated by Colaboratory.


Original file is located at
    https://colab.research.google.com/drive/1Rv1oPvBsz9gCvEpubte_X-sXid7vJeWV
"""

def template_1():
  Name = input("What is your name?")
  Adjective = input("Please insert an adjective")
  Color = input("What is your favorite color?")
  Animal = input("What is your favorite animal?")
  Place = input("What is your favorite city?")
  Adjective2 = input("Please insert an adjective")
  Magical_Creature = input("Name your fairytale creature in a plural form")
  Adjective3 = input("Please insert and adjective")
  Magical_Creature_2 = input("Name your favorite cartoon creature in a plural form")
  Room = input("What's your favorite room in a house?")
  Noun = input("What do you like to drink?")
  Noun2 = input("On what you put your head while sleeping?")
  Noun3 = input("How is called the soft furniture in living room?")
  Adjective4 = input("Please insert and adjective")
  Noun4 = input("Name one subject that you have on your desk")
  Number = input("How old are you?")
  Time = input('Please write the plural form of "month"')
  Verb = input('please insert the word "riding"')
  Adjective5 = input("PLease insert an adjective")
  Noun5 = input("What is your favorite means of transportaion?")

  print(f'''Dear {Name}, I am writing to you from a {Adjective} castle in an 
enchanted forest. I found myself here one day after going for a ride on a 
{Color} {Animal} in {Place}. There are {Adjective2} {Magical_Creature} and 
{Adjective3} {Magical_Creature_2} here! In the {Room} there is a pool full of 
{Noun}. I fall asleep each night on a {Noun2} of {Noun3} and dream of 
{Adjective4} {Noun4}. It feels as though I have lived here for {Number}{Time}. 
I hope one day you can visit, although the only way to get here now is {Verb} 
on a {Adjective5} {Noun5}!!''')



def template_2():
  Number = input("How old are you?")
  Time = input('Please write the plural form of "month"')
  Noun = input("What is your favorite means of transportaion?")
  Adjective = input("Please insert an adjective")
  Adjective2 = input("Please insert another adjective")
  Noun2 = input("What is your profession?")
  Color = input("What is your favorite color?")
  Body_part  = input("What is your favorite part of the body?")
  Verb = input('What should one do when they are hungry?')
  Number2 = input("How many time do you eat everyday?")
  Noun3 = input("What do you like to decorate your Christams tree with?")
  Noun4 = input("What is your favorite clothing attribute?")
  Body_part2  = input("What is your least favorite part of the body?")
  Verb2 = input('What should one do when they are hungry?')
  Noun5 = input("What do you like to eat?")
  Adjective3 = ("Please insert an adjective!")
  Silly_word = input("Say a silly word!")
  Noun6 = input("What's your favorite food?")
  
  print(f'''It was about {Number} {Time} ago when I arrived at the hospital in a 
{Noun}. The hospital is a/an {Adjective} place, there are a lot of {Adjective2} 
{Noun2} here. There are nurses here who have {Color} {Body_part}. If someone 
wants to come into my room I told them that they have  to {Verb} first. I’ve 
decorated my room with {Number2} {Noun3}. Today I talked to a doctor and they 
were wearing a {Noun4} on their {Body_part2}. I heard that all doctors {Verb2} 
{Noun5} every day for breakfast. The most {Adjective3} thing about being in the 
hospital is the {Silly_word} {Noun6}!''')

def template_3():
  Name = input("What is your name?")
  Noun = input("What do you like to drink?")
  Feeling = input("How do you feel?")
  Verb = input('What do you do when you are tired"')
  Feeling2 = input("How do you feel when you do something enjoyable?")
  Animal = input("What is your favorite animal?")
  Verb2 = input('What is your favorite hobby?')
  Color = input("What is your favorite color?")
  Verb3 = input('What insert a verb ending in "ing"?')
  Adverb = input("Please insert an adverb")
  Number = input("How old are you?")
  Time = input('Please write the plural form of "month"')
  Color2 = input("What is your least favorite color?")
  Animal2 = input("What is your least favorite animal?")
  Number2 = input("How many months there are in a year?")
  Silly_word = input("Say a silly word!")
  Noun2 = input("What's your favorite food?")
  
  print(f'''This weekend I am going camping with {Name}. I packed my lantern, 
sleeping bag, and {Noun}. I am so {Feeling} to {Verb} in a tent. I am {Feeling2} 
we might see a(n) {Animal2}, I hear they’re kind of dangerous. While we’re 
camping, we are going to hike, fish, and {Verb2}. I have heard that the {Color} 
lake is great for {Verb3}. Then we will {Adverb} hike through the forest for 
{Number} {Time}. If I see a {Color2} {Animal2} while hiking, I am going to bring 
it home as a pet! At night we will tell {Number2} {Silly_word} stories and roast 
{Noun2} around the campfire!!''')

import random 
ChoiceList = ["1", "2", "3"]
def game():
  if choice == "1":
    template_1()
  elif choice == "2":
    template_2()
  elif choice =="3":
    template_3()

name = input("What is your name?")
choice = input(f"""Hello, {name}. Please select one of the following options:
1
2
3
random
""")
if choice in ChoiceList:
  game()
elif choice == "random":
  choice = random.choice(ChoiceList)
  game()



